{"name": "test_answer", "status": "failed", "statusDetails": {"message": "AssertionError: assert 4 == 5\n +  where 4 = inc(3)", "trace": "def test_answer():\n>       assert inc(3) == 5\nE       assert 4 == 5\nE        +  where 4 = inc(3)\n\ntest_demo.py:7: AssertionError"}, "start": 1609831033070, "stop": 1609831033071, "uuid": "271a10a4-474a-45df-b7aa-aae4822fe521", "historyId": "8eb971d13b0d6a43fe517151dead2e2a", "testCaseId": "f09542d7d0cd3629beb2fa5024c22587", "fullName": "test_demo#test_answer", "labels": [{"name": "suite", "value": "test_demo"}, {"name": "host", "value": "jjiliu"}, {"name": "thread", "value": "43592-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_demo"}]}